controllers:
    resource: ../src/Controller/
    type: attribute
index:
    path: /
    defaults:
        _controller: App\Controller\BdeWebSiteController::app_bde_web_site
        _canonical_route: home

home:
    path: /home
    defaults:
        _controller: App\Controller\HomeController::home
user:
    resource: '../src/Controller/UserController.php'
    type: annotation
upload_success:
    path: /upload/success
    controller: App\Controller\ProjectController::uploadSuccess