controllers:
    resource: ../src/Controller/
    type: attribute
index:
    path: /
    defaults:
        _controller: App\Controller\HomeController::index
        _canonical_route: home

home:
    path: /home
    defaults:
        _controller: App\Controller\HomeController::home
user:
    resource: '../src/Controller/UserController.php'
    type: annotation
